/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_tower_defense;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author melan
 */
public class Interfaz_Grafica_Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    Cola tropasJugador = new Cola();
    public Cola tropasCPU = new Cola();
    public int numeroOleada = 1;
    Castillo castilloJugador = new Castillo(10);
    Castillo castilloCPU = new Castillo(10);
    int tropasAgregadas = 0;
    int numOleada = 1;
    int tropasDisponibles = numOleada + 4;
    double DanioaTorre;
    int contador = 1;
    
    private Timer ntimer;
    private int miliSegundos;
    private int segundos;
    private int minutos;
    private int horas;
    

    public Interfaz_Grafica_Juego() {
        initComponents();
        lbl_vidaJugador.setText(castilloJugador.getPuntosdeVida() + "");
        lbl_vidaCpu.setText(castilloCPU.getPuntosdeVida() + "");
        lbl_tropasDisponibles.setText(tropasDisponibles + "");
        lbl_tropasAgregadas.setText(tropasAgregadas + "");
        lbl_Oleada.setText(numOleada + "");
        ntimer = new Timer (10,(ActionEvent e) -> {
                inicioCronometro();
            
        });
    }
    
    private void inicioCronometro(){
        actualizarCronometro();
        actualizarLabel();
    }
    private void actualizarCronometro(){
        miliSegundos ++;
        
        if(miliSegundos == 60){
            miliSegundos = 0;
            segundos ++;
        }
        if(segundos == 60){
            segundos = 0;
            minutos ++;
        }
        if(minutos == 60){
            minutos = 0;
            horas ++;
        }
    }
    private void actualizarLabel(){
        String cronometro = horas + ":" + minutos + ":" + segundos + ":" + miliSegundos;
        LabelTiempo.setText(cronometro);
    }

    public void crearTropasCpu() {
        int c = 0;
        //Cola tropasCPU = new Cola();
        Juego juego = new Juego();
        while (c < (contador + 3)) {
            tropasCPU.encola(juego.generarTropasCpu());
            c++;
        }
        contador = contador + 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TorreJugador = new javax.swing.JLabel();
        TorreMaquina = new javax.swing.JLabel();
        LabelOleada = new javax.swing.JLabel();
        LBLqtyTropas = new javax.swing.JLabel();
        ImagenArquero = new javax.swing.JLabel();
        ImagenHechicero = new javax.swing.JLabel();
        LBLMagos1 = new javax.swing.JLabel();
        BntAgregarArquero = new java.awt.Button();
        ImagenCaballero = new javax.swing.JLabel();
        LBLCaballeros = new javax.swing.JLabel();
        LBLArqueros = new javax.swing.JLabel();
        BntAgregarMago = new java.awt.Button();
        BntAgregarCaballero = new java.awt.Button();
        LblOleada1 = new javax.swing.JLabel();
        BTNVolverMenu = new javax.swing.JButton();
        LBLVidaRestarteMaquina = new javax.swing.JLabel();
        LBLVidaRestarteJugador1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BNTIniciarOleada = new javax.swing.JButton();
        lbl_vidaJugador = new javax.swing.JLabel();
        lbl_vidaCpu = new javax.swing.JLabel();
        LblOleada2 = new javax.swing.JLabel();
        lbl_tropasDisponibles = new javax.swing.JLabel();
        lbl_tropasAgregadas = new javax.swing.JLabel();
        lbl_Oleada = new javax.swing.JLabel();
        LBLT3CPU = new javax.swing.JLabel();
        LBLT1CPU = new javax.swing.JLabel();
        LBLT2CPU = new javax.swing.JLabel();
        LBLTropa3 = new javax.swing.JLabel();
        LBLTropa1 = new javax.swing.JLabel();
        LBLTropa2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        TorreJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Torre.png"))); // NOI18N

        TorreMaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Torre.png"))); // NOI18N

        LabelOleada.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        LabelOleada.setForeground(new java.awt.Color(255, 255, 255));
        LabelOleada.setText("Oleada:");

        LBLqtyTropas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLqtyTropas.setForeground(new java.awt.Color(255, 255, 255));
        LBLqtyTropas.setText("Seleccione la tropa que desea enviar:");

        ImagenArquero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Arquero.png"))); // NOI18N

        ImagenHechicero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hechicero.png"))); // NOI18N
        ImagenHechicero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenHechiceroMouseClicked(evt);
            }
        });

        LBLMagos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LBLMagos1.setForeground(new java.awt.Color(255, 255, 255));
        LBLMagos1.setText("Magos");

        BntAgregarArquero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BntAgregarArquero.setLabel("¡Agregar tropa!");
        BntAgregarArquero.setPreferredSize(new java.awt.Dimension(26, 32));
        BntAgregarArquero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BntAgregarArqueroMouseClicked(evt);
            }
        });
        BntAgregarArquero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAgregarArqueroActionPerformed(evt);
            }
        });

        ImagenCaballero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Caballero.png"))); // NOI18N

        LBLCaballeros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LBLCaballeros.setForeground(new java.awt.Color(255, 255, 255));
        LBLCaballeros.setText("Caballeros");

        LBLArqueros.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LBLArqueros.setForeground(new java.awt.Color(255, 255, 255));
        LBLArqueros.setText("Arqueros");

        BntAgregarMago.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BntAgregarMago.setLabel("¡Agregar tropa!");
        BntAgregarMago.setPreferredSize(new java.awt.Dimension(26, 32));
        BntAgregarMago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BntAgregarMagoMouseClicked(evt);
            }
        });
        BntAgregarMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAgregarMagoActionPerformed(evt);
            }
        });

        BntAgregarCaballero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BntAgregarCaballero.setLabel("¡Agregar tropa!");
        BntAgregarCaballero.setPreferredSize(new java.awt.Dimension(26, 32));
        BntAgregarCaballero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BntAgregarCaballeroMouseClicked(evt);
            }
        });
        BntAgregarCaballero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAgregarCaballeroActionPerformed(evt);
            }
        });

        LblOleada1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblOleada1.setForeground(new java.awt.Color(255, 255, 255));
        LblOleada1.setText("Tropas disponibles:");

        BTNVolverMenu.setBackground(new java.awt.Color(255, 0, 51));
        BTNVolverMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        BTNVolverMenu.setText("Regresar al menú principal");
        BTNVolverMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTNVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverMenuActionPerformed(evt);
            }
        });

        LBLVidaRestarteMaquina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLVidaRestarteMaquina.setForeground(new java.awt.Color(255, 255, 255));
        LBLVidaRestarteMaquina.setText("Vida Restante: ");

        LBLVidaRestarteJugador1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLVidaRestarteJugador1.setForeground(new java.awt.Color(255, 255, 255));
        LBLVidaRestarteJugador1.setText("Vida Restante: ");

        BNTIniciarOleada.setBackground(new java.awt.Color(0, 153, 102));
        BNTIniciarOleada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BNTIniciarOleada.setForeground(new java.awt.Color(255, 255, 255));
        BNTIniciarOleada.setText("Iniciar Oleada");
        BNTIniciarOleada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNTIniciarOleada.setEnabled(false);
        BNTIniciarOleada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTIniciarOleadaActionPerformed(evt);
            }
        });

        lbl_vidaJugador.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lbl_vidaJugador.setForeground(new java.awt.Color(255, 255, 255));

        lbl_vidaCpu.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lbl_vidaCpu.setForeground(new java.awt.Color(255, 255, 255));

        LblOleada2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblOleada2.setForeground(new java.awt.Color(255, 255, 255));
        LblOleada2.setText("Tropas añadidas:");

        lbl_tropasDisponibles.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lbl_tropasDisponibles.setForeground(new java.awt.Color(255, 255, 255));

        lbl_tropasAgregadas.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lbl_tropasAgregadas.setForeground(new java.awt.Color(255, 255, 255));

        lbl_Oleada.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        lbl_Oleada.setForeground(new java.awt.Color(255, 255, 255));

        LBLTropa3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLTropa3.setForeground(new java.awt.Color(255, 255, 255));

        LBLTropa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLTropa1.setForeground(new java.awt.Color(255, 255, 255));

        LBLTropa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLTropa2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tiempo en Partida:");

        LabelTiempo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelTiempo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTiempo.setText("00:00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BntAgregarMago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(LBLMagos1))
                                            .addComponent(ImagenHechicero, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(98, 98, 98)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ImagenCaballero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(LBLCaballeros)))
                                        .addComponent(BntAgregarCaballero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(88, 88, 88))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(LBLVidaRestarteJugador1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_vidaJugador))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TorreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(136, 136, 136)
                                            .addComponent(LBLqtyTropas)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelTiempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                .addComponent(LabelOleada)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLArqueros)
                                    .addComponent(ImagenArquero, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbl_tropasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Oleada, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BntAgregarArquero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(536, 536, 536)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(BTNVolverMenu)
                                            .addGap(46, 46, 46)
                                            .addComponent(BNTIniciarOleada, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(279, 279, 279))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(LBLT1CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(LBLTropa1)
                                        .addGap(26, 26, 26)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LBLVidaRestarteMaquina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_vidaCpu))
                                    .addComponent(TorreMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LBLT2CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LBLT3CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(LBLTropa2)
                                        .addGap(44, 44, 44)
                                        .addComponent(LBLTropa3)))
                                .addGap(57, 57, 57))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblOleada2)
                                    .addComponent(LblOleada1))
                                .addGap(16, 16, 16)
                                .addComponent(lbl_tropasAgregadas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TorreMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LBLVidaRestarteMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_vidaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelOleada)
                                    .addComponent(lbl_Oleada))
                                .addGap(1, 1, 1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(LabelTiempo))
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TorreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLVidaRestarteJugador1)
                            .addComponent(lbl_vidaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTropa1)
                    .addComponent(LBLTropa3)
                    .addComponent(LBLTropa2)
                    .addComponent(LBLqtyTropas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLT2CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLT3CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLT1CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblOleada1)
                            .addComponent(lbl_tropasDisponibles))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LblOleada2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_tropasAgregadas)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ImagenHechicero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ImagenCaballero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(LBLMagos1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LBLCaballeros))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ImagenArquero, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLArqueros)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BntAgregarCaballero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BntAgregarArquero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BntAgregarMago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BNTIniciarOleada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BntAgregarArqueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAgregarArqueroActionPerformed
        Icon icono;
        icono = new ImageIcon(getClass().getResource("/Imagenes/ArqueroAtaque.png"));
        jLabel6.setIcon(icono);
        //Tropa arquero = new Arquero(1); 
        Nodo arquero = new Nodo(new Arquero(1));
        tropasJugador.encola(arquero);
        tropasAgregadas += 1;
        tropasDisponibles -= 1;
        lbl_tropasAgregadas.setText(tropasAgregadas + "");
        lbl_tropasDisponibles.setText(tropasDisponibles + "");
        if (tropasDisponibles == 0) {
            BntAgregarMago.setEnabled(false);
            BntAgregarCaballero.setEnabled(false);
            BntAgregarArquero.setEnabled(false);
            BNTIniciarOleada.setEnabled(true);
        }
    }//GEN-LAST:event_BntAgregarArqueroActionPerformed

    private void BntAgregarMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAgregarMagoActionPerformed
        Icon icono;
        icono = new ImageIcon(getClass().getResource("/Imagenes/HechiceroAtaque.png"));
        jLabel6.setIcon(icono);
        Nodo mago = new Nodo(new Mago(1.5));
        tropasJugador.encola(mago);
        tropasAgregadas += 1;
        tropasDisponibles -= 1;
        lbl_tropasAgregadas.setText(tropasAgregadas + "");
        lbl_tropasDisponibles.setText(tropasDisponibles + "");
        if (tropasDisponibles == 0) {
            BntAgregarMago.setEnabled(false);
            BntAgregarCaballero.setEnabled(false);
            BntAgregarArquero.setEnabled(false);
            BNTIniciarOleada.setEnabled(true);
        }
    }//GEN-LAST:event_BntAgregarMagoActionPerformed

    private void BntAgregarCaballeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAgregarCaballeroActionPerformed
        Icon icono;
        icono = new ImageIcon(getClass().getResource("/Imagenes/CaballeroAtaque.png"));
        jLabel6.setIcon(icono);
        Nodo caballero = new Nodo(new Caballero(2));
        tropasJugador.encola(caballero);
        tropasAgregadas += 1;
        tropasDisponibles -= 1;
        lbl_tropasAgregadas.setText(tropasAgregadas + "");
        lbl_tropasDisponibles.setText(tropasDisponibles + "");
        if (tropasDisponibles == 0) {
            BntAgregarMago.setEnabled(false);
            BntAgregarCaballero.setEnabled(false);
            BntAgregarArquero.setEnabled(false);
            BNTIniciarOleada.setEnabled(true);
        }
    }//GEN-LAST:event_BntAgregarCaballeroActionPerformed

    private void BTNVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverMenuActionPerformed
        Menu_Principal AbrirMePri = new Menu_Principal();
        AbrirMePri.setVisible(true);
        dispose();
    }//GEN-LAST:event_BTNVolverMenuActionPerformed

    private void BntAgregarCaballeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BntAgregarCaballeroMouseClicked
        // TODO add your handling code here:
        AudioClip sonidoCaballero;
        sonidoCaballero = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Caballero.wav"));
        sonidoCaballero.play();

    }//GEN-LAST:event_BntAgregarCaballeroMouseClicked

    private void ImagenHechiceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenHechiceroMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ImagenHechiceroMouseClicked

    private void BntAgregarMagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BntAgregarMagoMouseClicked
        // TODO add your handling code here:
        AudioClip sonidoMago;
        sonidoMago = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Mago.wav"));
        sonidoMago.play();
    }//GEN-LAST:event_BntAgregarMagoMouseClicked

    private void BntAgregarArqueroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BntAgregarArqueroMouseClicked
        // TODO add your handling code here:
        AudioClip sonidoArquera;
        sonidoArquera = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Arquera.wav"));
        sonidoArquera.play();
    }//GEN-LAST:event_BntAgregarArqueroMouseClicked

    private void BNTIniciarOleadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTIniciarOleadaActionPerformed
        // TODO add your handling code here:
        ntimer.start();
        JOptionPane.getRootFrame().setAlwaysOnTop(true);
        crearTropasCpu();
        int salir = 0;
        boolean gana = false;
        boolean empate = false;
        Nodo auxju = tropasJugador.getPrimerNodo();
        Nodo auxcpu = tropasCPU.getPrimerNodo();
        Nodo auxcpui = auxcpu;
        Icon icono;
        LBLTropa1.setText("Tropa 1");
        LBLTropa2.setText("Tropa 2");
        LBLTropa3.setText("Tropa 3");
        if (LBLT1CPU.getIcon() == null) {
            if (auxcpui.getTropa() instanceof Arquero) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Flecha.png"));
                LBLT1CPU.setIcon(icono);
            } else if (auxcpui.getTropa() instanceof Caballero) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Espadas.png"));
                LBLT1CPU.setIcon(icono);
            } else if (auxcpui.getTropa() instanceof Mago) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Magia.png"));
                LBLT1CPU.setIcon(icono);
            }
            auxcpui = auxcpui.getAtras();
        }
        if (LBLT2CPU.getIcon() == null) {
            if (auxcpui.getTropa() instanceof Arquero) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Flecha.png"));
                LBLT2CPU.setIcon(icono);
            } else if (auxcpui.getTropa() instanceof Caballero) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Espadas.png"));
                LBLT2CPU.setIcon(icono);
            } else if (auxcpui.getTropa() instanceof Mago) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Magia.png"));
                LBLT2CPU.setIcon(icono);
            }
            auxcpui = auxcpui.getAtras();
        }
        if (LBLT3CPU.getIcon() == null) {
            if (auxcpui.getTropa() instanceof Arquero) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Flecha.png"));
                LBLT3CPU.setIcon(icono);
            } else if (auxcpui.getTropa() instanceof Caballero) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Espadas.png"));
                LBLT3CPU.setIcon(icono);
            } else if (auxcpui.getTropa() instanceof Mago) {
                icono = new ImageIcon(getClass().getResource("/Imagenes/Magia.png"));
                LBLT3CPU.setIcon(icono);
            }
        }
        while (salir != 1) {
            if (auxju.getTropa() instanceof Arquero && auxcpu.getTropa() instanceof Mago) {
                AudioClip sonidoAtack;
                sonidoAtack = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Atack.wav"));
                sonidoAtack.play();
                JOptionPane.showMessageDialog(null, "Arquero V.S Mago \n GANAS");

                //
                auxcpu = auxcpu.getAtras();
                if (auxcpu == null) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Arquero && auxcpu.getTropa() instanceof Caballero) {
                AudioClip sonidoDamage;
                sonidoDamage = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Damage.wav"));
                sonidoDamage.play();
                JOptionPane.showMessageDialog(null, "Arquero V.S Caballero \n PIERDES");

                //
                auxju = auxju.getAtras();
                if (auxju == null) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Arquero && auxcpu.getTropa() instanceof Arquero) {
                JOptionPane.showMessageDialog(null, "Arquero V.S Arquero \n EMPATE");
                //
                auxju = auxju.getAtras();
                auxcpu = auxcpu.getAtras();
                if ((auxcpu == null) || (auxju == null)) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Caballero && auxcpu.getTropa() instanceof Arquero) {
                AudioClip sonidoAtack;
                sonidoAtack = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Atack.wav"));
                sonidoAtack.play();
                JOptionPane.showMessageDialog(null, "Caballero V.S Arquero \n GANAS");

                //
                auxcpu = auxcpu.getAtras();
                if (auxcpu == null) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Caballero && auxcpu.getTropa() instanceof Mago) {
                AudioClip sonidoDamage;
                sonidoDamage = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Damage.wav"));
                sonidoDamage.play();
                JOptionPane.showMessageDialog(null, "Caballero V.S Mago \n PIERDES");

                //
                auxju = auxju.getAtras();
                if (auxju == null) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Caballero && auxcpu.getTropa() instanceof Caballero) {
                JOptionPane.showMessageDialog(null, "Caballero V.S Caballero \n EMPATE");
                //
                auxju = auxju.getAtras();
                auxcpu = auxcpu.getAtras();
                if ((null == auxcpu) || (auxju == null)) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Mago && auxcpu.getTropa() instanceof Caballero) {
                AudioClip sonidoAtack;
                sonidoAtack = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Atack.wav"));
                sonidoAtack.play();
                JOptionPane.showMessageDialog(null, "Mago V.S Caballero \n GANAS");

                //
                auxcpu = auxcpu.getAtras();
                if (auxcpu == null) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Mago && auxcpu.getTropa() instanceof Arquero) {
                AudioClip sonidoDamage;
                sonidoDamage = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Damage.wav"));
                sonidoDamage.play();
                JOptionPane.showMessageDialog(null, "Mago V.S Arquero \n PIERDES");

                //
                auxju = auxju.getAtras();
                if (auxju == null) {
                    salir = 1;
                }
            } else if (auxju.getTropa() instanceof Mago && auxcpu.getTropa() instanceof Mago) {
                JOptionPane.showMessageDialog(null, "Mago V.S Mago \n EMPATE");
                //
                auxju = auxju.getAtras();
                auxcpu = auxcpu.getAtras();
                if ((auxcpu == null) || (auxju == null)) {
                    salir = 1;
                }
            }
            if ((auxju == null) && (auxcpu == null)) {
                empate = true;
            } else if ((auxju != null) && (auxcpu == null)) {
                gana = true;
            } else if ((auxju == null) && (auxcpu != null)) {
                gana = false;
            }
        }
        if ((gana == true) && (empate == false)) {
            while (auxju != null) {
                if (auxju.getTropa() instanceof Mago) {
                    DanioaTorre = DanioaTorre + 1.5;
                } else if (auxju.getTropa() instanceof Caballero) {
                    DanioaTorre = DanioaTorre + 2;
                } else if (auxju.getTropa() instanceof Arquero) {
                    DanioaTorre = DanioaTorre + 1;
                }
                auxju = auxju.getAtras();
            }
            AudioClip sonidoCelebrate;
            sonidoCelebrate = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Ahuevo.wav"));
            sonidoCelebrate.play();
            JOptionPane.showMessageDialog(null, "¡Felicidades, usted gano esta oleada y ejerció " + DanioaTorre + " a la torre enemiga!");

            castilloCPU.recibirAtaque(DanioaTorre);
        } else if ((gana == false) && (empate == false)) {
            while (auxcpu != null) {
                if (auxcpu.getTropa() instanceof Mago) {
                    DanioaTorre = DanioaTorre + 1.5;
                } else if (auxcpu.getTropa() instanceof Caballero) {
                    DanioaTorre = DanioaTorre + 2;
                } else if (auxcpu.getTropa() instanceof Arquero) {
                    DanioaTorre = DanioaTorre + 1;
                }
                auxcpu = auxcpu.getAtras();
            }
            AudioClip SonidoDerrota;
            SonidoDerrota = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Derrota.wav"));
            SonidoDerrota.play();
            JOptionPane.showMessageDialog(null, "¡Derrota! El enemigo ejerció " + DanioaTorre + " a la su torre");
            castilloJugador.recibirAtaque(DanioaTorre);
        } else if (empate == true) {
            JOptionPane.showMessageDialog(null, "¡Empate! Logró defenderse de los ataques enemigos exitosamente");
        }
        numOleada++;
        jLabel6.setIcon(null);
        tropasDisponibles = numOleada + 4;
        tropasAgregadas = 0;
        lbl_Oleada.setText(numOleada + "");
        lbl_tropasAgregadas.setText(tropasAgregadas + "");
        lbl_tropasDisponibles.setText(tropasDisponibles + "");
        lbl_vidaJugador.setText(castilloJugador.getPuntosdeVida() + "");
        lbl_vidaCpu.setText(castilloCPU.getPuntosdeVida() + "");
        LBLT1CPU.setIcon(null);
        LBLTropa1.setText(null);
        LBLT2CPU.setIcon(null);
        LBLTropa2.setText(null);
        LBLT3CPU.setIcon(null);
        LBLTropa3.setText(null);
        DanioaTorre = 0;
        tropasJugador.vaciarCola();
        tropasCPU.vaciarCola();
        BntAgregarCaballero.setEnabled(true);
        BntAgregarArquero.setEnabled(true);
        BntAgregarMago.setEnabled(true);
        BNTIniciarOleada.setEnabled(false);
        if ((castilloJugador.getPuntosdeVida() == 0) || (castilloCPU.getPuntosdeVida() == 0)) {
            if (castilloJugador.getPuntosdeVida() == 0) {
                AudioClip sonidoLoser;
                sonidoLoser = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Game Over Mario.wav"));
                sonidoLoser.play();
                ntimer.stop();
                miliSegundos = 0;
                segundos = 0;
                minutos = 0;
                horas = 0;
                JOptionPane.showMessageDialog(this, "GAME OVER");
                
                

            } else if (castilloCPU.getPuntosdeVida() == 0) {
                AudioClip sonidoWin;
                sonidoWin = java.applet.Applet.newAudioClip(getClass().getResource("/proyecto_tower_defense/Sonido Win Mario.wav"));
                sonidoWin.play();
                ntimer.stop();
                miliSegundos = 0;
                segundos = 0;
                minutos = 0;
                horas = 0;
                JOptionPane.showMessageDialog(this, "YOU WIN");
                
                
            }
            contador = 1;
            jLabel6.setIcon(null);
            numOleada = 1;
            castilloJugador.setPuntosdeVida(10);
            castilloCPU.setPuntosdeVida(10);
            tropasDisponibles = numOleada + 4;
            tropasAgregadas = 0;
            lbl_vidaJugador.setText(castilloJugador.getPuntosdeVida() + "");
            lbl_vidaCpu.setText(castilloCPU.getPuntosdeVida() + "");
            lbl_tropasAgregadas.setText(tropasAgregadas + "");
            lbl_tropasDisponibles.setText(tropasDisponibles + "");
            lbl_Oleada.setText(numOleada + "");
            tropasJugador.vaciarCola();
            tropasCPU.vaciarCola();
            LBLTropa1.setText(null);
            LBLT2CPU.setIcon(null);
            LBLTropa2.setText(null);
            LBLT3CPU.setIcon(null);
            LBLTropa3.setText(null);
            BNTIniciarOleada.setEnabled(false);
        }
        /**/
    }//GEN-LAST:event_BNTIniciarOleadaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNTIniciarOleada;
    private javax.swing.JButton BTNVolverMenu;
    private java.awt.Button BntAgregarArquero;
    private java.awt.Button BntAgregarCaballero;
    private java.awt.Button BntAgregarMago;
    private javax.swing.JLabel ImagenArquero;
    private javax.swing.JLabel ImagenCaballero;
    private javax.swing.JLabel ImagenHechicero;
    private javax.swing.JLabel LBLArqueros;
    private javax.swing.JLabel LBLCaballeros;
    private javax.swing.JLabel LBLMagos1;
    private javax.swing.JLabel LBLT1CPU;
    private javax.swing.JLabel LBLT2CPU;
    private javax.swing.JLabel LBLT3CPU;
    private javax.swing.JLabel LBLTropa1;
    private javax.swing.JLabel LBLTropa2;
    private javax.swing.JLabel LBLTropa3;
    private javax.swing.JLabel LBLVidaRestarteJugador1;
    private javax.swing.JLabel LBLVidaRestarteMaquina;
    private javax.swing.JLabel LBLqtyTropas;
    private javax.swing.JLabel LabelOleada;
    private javax.swing.JLabel LabelTiempo;
    private javax.swing.JLabel LblOleada1;
    private javax.swing.JLabel LblOleada2;
    private javax.swing.JLabel TorreJugador;
    private javax.swing.JLabel TorreMaquina;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Oleada;
    private javax.swing.JLabel lbl_tropasAgregadas;
    private javax.swing.JLabel lbl_tropasDisponibles;
    private javax.swing.JLabel lbl_vidaCpu;
    private javax.swing.JLabel lbl_vidaJugador;
    // End of variables declaration//GEN-END:variables
}
